[project]
name = "swiftllm-c"
version = "0.0.2"
description = "Some C++/CUDA sources for SwiftLLM."
authors = [{ name = "Sao-Hsuan Lin", email = "saohsuan@lsalab.cs.nthu.edu.tw" }]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
]

[build-system]
requires = ["setuptools>=61.0", "torch", "wheel"]
build-backend = "setuptools.build_meta"
